name: Code Build and Deployment on K8s 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on Infrastructure Code
        continue-on-error: true
        run: |
          checkov -d ./k8s \
            --framework terraform,kubernetes,cloudformation \
            --output json \
            --output-file checkov-report.json \
            --skip-check BC.PipelineMissing

      - name: Upload Checkov Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-reports
          path: checkov-report.json

      - name: Set up Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/smart-health-monitoring-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/smart-health-monitoring-app:${{ github.sha }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update GitOps
        run: |
          yq eval ".spec.template.spec.containers[0].image = \"${{ secrets.DOCKER_USERNAME }}/smart-health-monitoring-app:${{ github.sha }}\"" -i k8s/smart-health-app/Deployment.yml

      - name: Commit and Push GitOps
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/smart-health-app/Deployment.yml
          git commit -m "Update image to ${{ secrets.DOCKER_USERNAME }}/smart-health-monitoring-app:${{ github.sha }}"
          git push origin main
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}

